version: '2'
services:
  backend:
    container_name: nm-medical-instituion-container
    image: limavi2015/medical-institution
    ports:
      - 3789:3789
    links:
      - mongo
    depends_on:
      - mongo 
  mongo:
    container_name: nm-mongo-container
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
